#!/bin/bash
(printf '%s\n' . ..  ls -1A | sort -d -f -t/ -k1.1,1.1 -k1.2n) | paste -sd ',' -  echo
(echo .; echo .. ls -1A | grep -vE '^(\.|..)$' | LC_ALL=C sort -t/ -k1.1,1.1 -k1.2n) | paste -sd ',' -  echo
